services:

  api:
    container_name: news-api
    build: .
    command: >
      python -m debugpy --listen 0.0.0.0:5678
      -m uvicorn api.news_api:app --host 0.0.0.0 --port 8080 --reload
    ports:
      - "8080:8080"
      - "5678:5678"
    environment:
      - MONGO_URI=mongodb://admin:secret@db:27017
      - MONGO_DB=news
    depends_on:
      - db

  db:
    container_name: news-db
    image: mongo:6
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  crawlers:
    container_name: news-crawlers
    build: .
    command: python -m scripts.crawl_scheduler
    environment:
      - CRAWLING_AFTER_START=false
      - MONGO_URI=mongodb://admin:secret@db:27017
      - MONGO_DB=news
    depends_on:
      - db

volumes:
  mongo_data:
